// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpj_SQtPx7CCKT6VrSNxuaX8rhbq4oIBY',
    appId: '1:154040250629:web:068acb619729082d4d476c',
    messagingSenderId: '154040250629',
    projectId: 'delivery-app-2fe1b',
    authDomain: 'delivery-app-2fe1b.firebaseapp.com',
    storageBucket: 'delivery-app-2fe1b.firebasestorage.app',
    measurementId: 'G-Q4F1MMMS8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD10XedfSKr9BhcFGVzDqwFCFsiK6H2wAI',
    appId: '1:154040250629:android:0b6b8b03aca6c51b4d476c',
    messagingSenderId: '154040250629',
    projectId: 'delivery-app-2fe1b',
    storageBucket: 'delivery-app-2fe1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK8G8pWgAVilJYLBCgkTCW_-Ptz-ft6vA',
    appId: '1:154040250629:ios:11a975afe0b4e8364d476c',
    messagingSenderId: '154040250629',
    projectId: 'delivery-app-2fe1b',
    storageBucket: 'delivery-app-2fe1b.firebasestorage.app',
    iosClientId: '154040250629-do2s9g81vaolruglum0ehao6ojse3945.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK8G8pWgAVilJYLBCgkTCW_-Ptz-ft6vA',
    appId: '1:154040250629:ios:11a975afe0b4e8364d476c',
    messagingSenderId: '154040250629',
    projectId: 'delivery-app-2fe1b',
    storageBucket: 'delivery-app-2fe1b.firebasestorage.app',
    iosClientId: '154040250629-do2s9g81vaolruglum0ehao6ojse3945.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpj_SQtPx7CCKT6VrSNxuaX8rhbq4oIBY',
    appId: '1:154040250629:web:6d0276a24878f5024d476c',
    messagingSenderId: '154040250629',
    projectId: 'delivery-app-2fe1b',
    authDomain: 'delivery-app-2fe1b.firebaseapp.com',
    storageBucket: 'delivery-app-2fe1b.firebasestorage.app',
    measurementId: 'G-JPWZQ0261S',
  );
}
